name: "fsadykov/common-action"
author: "Farkhod Sadykov"
branding:
  icon: "git-branch"
  color: "gray-dark"
description: "Publish Common actions from an action"

inputs:
  title:
    description: "The name of the release to publish"
    required: true

runs:
  using: 'composite'
  steps:      
    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        INPUT_TITLE: ${{ inputs.title }}
